### Generate Legends cards

POST http://localhost:7071/api/game/heat/legends/generate
Content-Type: application/json

{
    "difficulty": "Easy",
    "useSilver": true,
    "useRed": false,
    "useOrange": false,
    "useGreen": false,
    "useBlack": false,
    "usePurple": false,
    "useBlue": false,
    "useYellow": false
}

###